development:
  bucket_name: getmocha-development
  access_key_id: AKIAJQ575MT55SYOALSA
  secret_access_key: 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
  #~ distribution_domain: XXXX.cloudfront.net

test:
  bucket_name: getmocha-test
  access_key_id: AKIAJQ575MT55SYOALSA
  secret_access_key: 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
  #~ distribution_domain: XXXX.cloudfront.net
  
staging:
  bucket_name: getmocha-staging
  access_key_id: AKIAJQ575MT55SYOALSA
  secret_access_key: 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
  #~ distribution_domain: XXXX.cloudfront.net

production:
  bucket_name: getmocha-production
  access_key_id: AKIAJQ575MT55SYOALSA
  secret_access_key: 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
  #~ distribution_domain: XXXX.cloudfront.net
